-- AlterTable
ALTER TABLE "TrustBarWidget" ADD COLUMN     "advanceCss" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "fontSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN     "fontWeight" TEXT NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN     "hideIfNoReviews" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "reviewSource" TEXT NOT NULL DEFAULT 'DEMO_REVIEW_SOURCE',
ADD COLUMN     "showAverageRating" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showReviewCount" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showVerifiedBadge" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "starColor" TEXT NOT NULL DEFAULT '#F59E0B',
ADD COLUMN     "starSize" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN     "textColor" TEXT NOT NULL DEFAULT '#1A1A1A',
ADD COLUMN     "verifiedBadgeColor" TEXT NOT NULL DEFAULT '#088728';
